### PR TITLE
Add XMLHttpRequest functionality necessary to make requests

### PR DESCRIPTION
**Pull request by ali-abrar**

### CODE REVIEW

**Comment by hamishmack** [comment]
This is a generated file (created using [this](https://github.com/ghcjs/domconv-webkit/blob/master/domconv-webkit-jsffi.hs) rather hacking code).  I have updated it to include the missing functions except the code to call `new XMLHttpRequest()`.  It looks like there is a `Constructor` attribute on the interface that we can use to figure out which interfaces in the IDL require this.

**Comment by xionite** [comment]
My mistake. Where can I find the IDL files used by the generator? Thanks for pointing me in the right direction.

**Comment by geraldus** [comment]
Good! Recently I've had to implement this stuff myself in my current project.

**Comment by xionite** [comment]
Hi, could you let me know where I can get the IDL files you're using? I don't want to end up with a different version. Thanks.

**Comment by hamishmack** [comment]
The IDL files are included in [webkitgtk](http://webkitgtk.org/).  I have been working on some more changes to the domconv that are not quite finished.  I'll try to update domconv and ghcjs-dom this week.  To run the generator I use something like `domconv-webkit-jsffi webkit.idl -I/Users/hamish/build/webkitgtk-2.7.2/Source/WebCore` in the ghcjs-dom root dir.  If you have any suggestions (but not enough time to update domconv), feel free to submit a pull request with an example of the sort of change you would like to see and I will try to include it in the domconv code.

**Comment by hamishmack** [comment]
I think everything needed is generated now [here](https://github.com/ghcjs/ghcjs-dom/blob/master/src/GHCJS/DOM/JSFFI/Generated/XMLHttpRequest.hs#L35) or in the non generated module [here](https://github.com/ghcjs/ghcjs-dom/blob/master/src/GHCJS/DOM/JSFFI/XMLHttpRequest.hs).

**Pull request closed without merging**
